 "use client";
import AppShell from "@/components/AppShell"; import {useEffect,useMemo,useRef,useState} from "react";
type P={id:string;barcode:string;name:string;price:number;stock:number}; type C=P&{qty:number;discount:number};
const products:P[]=[{id:"p1",barcode:"7501055300011",name:"Coca Cola 600 ml",price:18,stock:42},{id:"p2",barcode:"7501055300012",name:"Coca Cola 1.5 L",price:29,stock:28},{id:"p3",barcode:"7501000123456",name:"Agua 1 L",price:14,stock:80},{id:"p4",barcode:"7501012345678",name:"Pan Blanco",price:42,stock:5},{id:"p5",barcode:"7501098765432",name:"Leche 1 L",price:28,stock:0}];

export default function Pos(){const [q,setQ]=useState("");const [cart,setCart]=useState<C[]>([]);const [pay,setPay]=useState(false);const [received,setReceived]=useState("");const [ticket,setTicket]=useState<string|null>(null);const inputRef=useRef<HTMLInputElement>(null);
const filtered=products.filter(p=>(p.name+" "+p.barcode).toLowerCase().includes(q.toLowerCase()));
const subtotal=useMemo(()=>cart.reduce((s,x)=>s+x.price*x.qty-x.discount,0),[cart]); const total=subtotal; const change=Math.max(0,(Number(received)||0)-total);
function add(p:P){if(p.stock<=0)return;setCart(c=>{const e=c.find(x=>x.id===p.id);if(e&&e.qty<p.stock)return c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x);if(e)return c;return [...c,{...p,qty:1,discount:0}]})}
useEffect(()=>{const on=(e:KeyboardEvent)=>{if(e.key==="F2"){e.preventDefault();inputRef.current?.focus()}if(e.key==="F4"){e.preventDefault();if(cart.length)setPay(true)}};window.addEventListener("keydown",on);return()=>window.removeEventListener("keydown",on)},[cart.length]);
function simulateScan(){const p=products.find(x=>x.barcode===q.trim());if(p)add(p);setQ("");inputRef.current?.focus()}
return <AppShell role="CASHIER"><div className="pos"><section><h1 className="title">Punto de Venta</h1><p className="subtitle">Tienda 001 · Cajero demo · F2 buscar · F4 cobrar</p><div className="toolbar"><input ref={inputRef} autoFocus className="input" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")simulateScan()}} placeholder="Escanea código o busca producto..."/><button className="btn" onClick={simulateScan}>Agregar código</button><button className="btn">📷 Escanear cámara</button></div><div className="productGrid">{filtered.map(p=><button className="productCard" key={p.id} onClick={()=>add(p)}><h3>{p.name}</h3><p className="muted">{p.barcode}</p><div className="price">${p.price.toFixed(2)}</div><span className={`badge ${p.stock===0?"danger":p.stock<=5?"warn":"ok"}`}>{p.stock===0?"Agotado":`Stock ${p.stock}`}</span></button>)}</div></section><aside className="card cart"><h2>Carrito</h2>{cart.length===0?<p className="muted">No hay productos.</p>:cart.map(x=><div className="cartRow" key={x.id}><div style={{display:"flex",justifyContent:"space-between"}}><strong>{x.name}</strong><strong>${(x.price*x.qty-x.discount).toFixed(2)}</strong></div><div style={{display:"flex",justifyContent:"space-between",marginTop:7}}><span className="muted">{x.qty} × ${x.price.toFixed(2)}</span><div><button className="btn" onClick={()=>setCart(c=>c.map(y=>y.id===x.id?{...y,qty:Math.max(1,y.qty-1)}:y))}>−</button> <button className="btn" onClick={()=>add(x)}>+</button> <button className="btn btnDanger" onClick={()=>setCart(c=>c.filter(y=>y.id!==x.id))}>×</button></div></div></div>)}<div style={{marginTop:16,display:"grid",gap:9}}><div style={{display:"flex",justifyContent:"space-between"}}><span>Subtotal</span><strong>${subtotal.toFixed(2)}</strong></div><div style={{display:"flex",justifyContent:"space-between"}}><span>Descuento</span><strong>$0.00</strong></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span>Total</span><span className="total">${total.toFixed(2)}</span></div><button className="btn btnPrimary btnWide" disabled={!cart.length} onClick={()=>setPay(true)}>COBRAR</button></div></aside></div>
{pay&&<div className="modalBack"><div className="modal"><div style={{display:"flex",justifyContent:"space-between"}}><h2>Cobro</h2><button className="btn" onClick={()=>setPay(false)}>Cerrar</button></div><div className="grid grid2"><div className="card"><div className="muted">Total a pagar</div><div className="total">${total.toFixed(2)}</div></div><div className="field"><label className="label">Método</label><select className="select"><option>Efectivo</option><option>Tarjeta</option><option>Transferencia</option></select></div></div><div className="field" style={{marginTop:14}}><label className="label">Efectivo recibido</label><input className="input" type="number" step="0.01" value={received} onChange={e=>setReceived(e.target.value)} placeholder="0.00"/></div><div className="card" style={{marginTop:14}}><div className="muted">Cambio</div><div className="total">${change.toFixed(2)}</div></div><div className="toolbar"><button className="btn btnPrimary" onClick={()=>{const t="T-"+Date.now().toString().slice(-8);setTicket(t);setPay(false);setCart([]);setReceived("")}}>CONFIRMAR PAGO</button></div></div></div>}
{ticket&&<div className="modalBack"><div className="modal"><div style={{display:"flex",justifyContent:"space-between"}}><h2>Venta completada</h2><button className="btn noPrint" onClick={()=>setTicket(null)}>Cerrar</button></div><div className="ticket" id="ticket"><h2 style={{textAlign:"center",margin:0}}>MI NEGOCIO</h2><p style={{textAlign:"center",margin:"4px 0"}}>Ticket {ticket}</p><hr/><table><tbody><tr><td>Coca Cola / ejemplo</td><td className="right">Ver detalle</td></tr></tbody></table><hr/><div style={{display:"flex",justifyContent:"space-between"}}><strong>TOTAL</strong><strong>${total.toFixed(2)}</strong></div><p style={{fontSize:12}}>Método: Efectivo · Cajero: Demo · Tienda: 001</p></div><div className="toolbar noPrint"><button className="btn btnPrimary" onClick={()=>window.print()}>Imprimir ticket</button></div></div></div>}</AppShell>}